# Generated by Django 3.1.1 on 2020-09-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('FUND', 'Fundacja'), ('OPOZ', 'Organizacja pozarządowa'), ('ZLOK', 'Zbiórka lokalna')], default='FUND', max_length=4)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(to='inkind.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=150, verbose_name='Ulica i numer domu')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.DateTimeField()),
                ('pick_up_comment', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='inkind.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkind.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
