# Generated by Django 3.1.1 on 2020-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0004_auto_20200926_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Użytkownik z takim mailem już istnieje.'}, max_length=255, unique=True, verbose_name='Email adres'),
        ),
    ]
